#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Aria2-Pro-Core
#

name: Aria2 Builder

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        ./aria2-gnu-linux-build-amd64.sh


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aria2-static-linux-amd64.tar.gz
        path: /tmp/aria2/src/output

